-- MySQL Script generated by MySQL Workbench
-- Mon May  5 00:33:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bufi_finance
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bufi_finance` ;

-- -----------------------------------------------------
-- Schema bufi_finance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bufi_finance` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bufi_finance` ;

-- -----------------------------------------------------
-- Table `bufi_finance`.`cashflow_projections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`cashflow_projections` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`cashflow_projections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projection_date` DATE NOT NULL,
  `projected_inflow` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `projected_outflow` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `actual_inflow` DECIMAL(12,2) NULL DEFAULT NULL,
  `actual_outflow` DECIMAL(12,2) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_cashflow_date` ON `bufi_finance`.`cashflow_projections` (`projection_date` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bufi_finance`.`customer_segments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`customer_segments` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`customer_segments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `segment_name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bufi_finance`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`customers` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `segment_id` INT NULL DEFAULT NULL,
  `business_size` ENUM('Small', 'Medium', 'Large', 'Enterprise') NOT NULL,
  `acquisition_date` DATE NULL DEFAULT NULL,
  `lifetime_value` DECIMAL(12,2) NULL DEFAULT '0.00',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `customers_ibfk_1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `bufi_finance`.`customer_segments` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_customers_segment` ON `bufi_finance`.`customers` (`segment_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bufi_finance`.`expense_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`expense_categories` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`expense_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_fixed` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bufi_finance`.`kpi_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`kpi_metrics` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`kpi_metrics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metric_name` VARCHAR(50) NOT NULL,
  `metric_value` DECIMAL(12,2) NOT NULL,
  `target_value` DECIMAL(12,2) NOT NULL,
  `metric_date` DATE NOT NULL,
  `metric_type` ENUM('percentage', 'currency', 'number', 'ratio') NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_kpi_date` ON `bufi_finance`.`kpi_metrics` (`metric_date` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bufi_finance`.`revenue_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`revenue_categories` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`revenue_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bufi_finance`.`sales_funnel_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`sales_funnel_entries` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`sales_funnel_entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL DEFAULT NULL,
  `stage_id` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  `exit_date` DATE NULL DEFAULT NULL,
  `value` DECIMAL(12,2) NULL DEFAULT NULL,
  `converted` TINYINT(1) NULL DEFAULT '0',
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `sales_funnel_entries_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bufi_finance`.`customers` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `sales_funnel_entries_ibfk_2`
    FOREIGN KEY (`stage_id`)
    REFERENCES `bufi_finance`.`sales_stages` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `customer_id` ON `bufi_finance`.`sales_funnel_entries` (`customer_id` ASC) VISIBLE;

CREATE INDEX `idx_sales_funnel_stage` ON `bufi_finance`.`sales_funnel_entries` (`stage_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bufi_finance`.`sales_stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`sales_stages` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`sales_stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stage_name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `stage_order` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bufi_finance`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`transactions` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATE NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `type` ENUM('revenue', 'expense') NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `recurring` TINYINT(1) NULL DEFAULT '0',
  `recurring_frequency` ENUM('daily', 'weekly', 'monthly', 'quarterly', 'annually') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `transactions_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bufi_finance`.`customers` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `customer_id` ON `bufi_finance`.`transactions` (`customer_id` ASC) VISIBLE;

CREATE INDEX `idx_transactions_date` ON `bufi_finance`.`transactions` (`transaction_date` ASC) VISIBLE;

CREATE INDEX `idx_transactions_type` ON `bufi_finance`.`transactions` (`type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bufi_finance`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bufi_finance`.`users` ;

CREATE TABLE IF NOT EXISTS `bufi_finance`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `full_name` VARCHAR(100) NULL DEFAULT NULL,
  `role` ENUM('admin', 'user') NULL DEFAULT 'user',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `username` ON `bufi_finance`.`users` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `email` ON `bufi_finance`.`users` (`email` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
